name: Resolve automation settings

on:
  workflow_call:
    outputs:
      enabled:
        value: ${{ jobs.resolve-automation.outputs.enabled == 'true' }}
      token:
        value: ${{ jobs.resolve-automation.outputs.token }}
      username:
        value: ${{ vars.AUTOMATION_USERNAME }}
      email:
        value: ${{ vars.AUTOMATION_EMAIL }}
    secrets:
      OTELBOT_PRIVATE_KEY:
        required: false

jobs:
  resolve-automation:

    runs-on: ubuntu-22.04

    outputs:
      enabled: ${{ steps.evaluate.outputs.enabled }}
      token: ${{ steps.otelbot-token.outputs.token }}

    steps:
    - uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
      id: otelbot-token
      with:
        app-id: ${{ vars.OTELBOT_APP_ID }}
        private-key: ${{ secrets.OTELBOT_PRIVATE_KEY }}
        
    - id: evaluate
      env:
        OTELBOT_TOKEN_EXISTS: ${{ steps.otelbot-token.outputs.token != '' }}
      run: |
        echo "enabled=${{ env.OTELBOT_TOKEN_EXISTS == 'true' }}" >> "$GITHUB_OUTPUT"
